### ISSUE TITLE
How to change image dynamically

### ISSUE THREAD

**Issue by Oliver530** [EurekaCommunity/ViewRow#14]
First of all, many thanks for the functionality. That's exactly what I was looking for.

How can I change the content of the series dynamically? 

`viewRowImage?.cell.view?.image = image` has no effect on the _viewDidAppear_-Trigger. Updating the row with `updateCell()` or `reload()` does not help either.

I would be very happy about your help.

**Comment by alldritt** [comment]
How are you acquiring the `viewRowImage` value?  Are you sure its non-nil?  When I tested it here, all I need to do is assign a new image to the `viewRowImage?.cell.view?.image`.  I've updated my example application to illustrate this - pull a fresh copy to see this in `ImageViewViewController.swift`.

Here's the example code I'm using:

~~~~
            +++ Section("Image View with changable image")
            
                <<< SegmentedRow<String> { (row) in
                    row.title = "Image"
                    row.options = ["trees", "flower"]
                    row.value = "trees"
                }
                .cellSetup { (cell, row) in
                    cell.segmentedControl.setContentHuggingPriority(UILayoutPriority(rawValue: 750), for: .horizontal)
                    cell.segmentedControl.apportionsSegmentWidthsByContent = true
                }
                .onChange { [unowned self] (row) in
                    guard let imageName = row.value else { return }
                    guard let imageRow = self.form.rowBy(tag: "xxxx") as? ViewRow<UIImageView> else { return }
                    
                    let image = UIImage(named: imageName)
                    imageRow.cell.view!.image = image
                }

                <<< ViewRow<UIImageView>("xxxx")
                .cellSetup { (cell, row) in
                    //  Construct the view for the cell
                    cell.view = UIImageView(frame: CGRect(x: 0, y: 0, width: 100, height: 300))
                    cell.view!.contentMode = .scaleAspectFill
                    cell.view!.clipsToBounds = true
                    
                    //  Get something to display
                    let image = UIImage(named: "trees")
                    cell.view!.image = image
                    
                    //  Make the image view occupy the entire row:
                    cell.viewRightMargin = 0.0
                    cell.viewLeftMargin = 0.0
                    cell.viewTopMargin = 0.0
                    cell.viewBottomMargin = 0.0
                }
~~~~

Here's hat this looks like when running:

![screenflow](https://user-images.githubusercontent.com/1425137/39894520-f71f2df4-545b-11e8-852f-59f715b4bd55.gif)

**Comment by Oliver530** [comment]
Thanks a lot for your super-fast help! I found the mistake on my side:
I set the cell's _tag_ in the cellSetup()-function via `row.tag = "myID"` instead of passing it to the constructor. This meant that I could not reference the row.

Thanks for updating the example!
