### ISSUE TITLE
Eureka 5.0.0 compatibility issues

### ISSUE THREAD

**Issue by shi-rudo** [EurekaCommunity/ViewRow#20]
After upgrading to Eureka 5.0.0

`Compiling for iOS 8.0, but module 'Eureka' has a minimum deployment target of iOS 9.3: /Users/dennis/Library/Developer/Xcode/DerivedData/../Eureka.swiftmodule/arm64.swiftmodule`

**Comment by alldritt** [comment]
This sounds like an issue for the Eureka group.  I'll probably increase ViewRow's minimum version from 8.0 to 9.3 to match Eureka.
