### ISSUE TITLE
Is the README outdated?

### ISSUE THREAD

**Issue by Sweeper777** [EurekaCommunity/ViewRow#6]
In the README, `ViewRow` is shown to have a generic parameter, but when I installed the pod (version 0.2.0), `ViewRow` is not a generic class.

Is the README outdated?

**Comment by alldritt** [comment]
The README file is up to date.  ViewRow is a generic class:

```
public final class ViewRow<ViewType : UIView>: _ViewRow<ViewType>, RowType { ... }
```

**Comment by Sweeper777** [comment]
But somehow I can use it without the generic argument. Isn't that weird?

**Comment by alldritt** [comment]
In that case, you are specifying that ViewRow's view property of type UIView.

**Comment by Sweeper777** [comment]
I've never seen that behaviour in swift before... anyway, thanks for the info!
