### ISSUE TITLE
shouldn't this read subclass not sunclass

### ISSUE THREAD

**Issue by donhill** [EurekaCommunity/ViewRow#7]
UIView (or UIView sunclass) should this be "UIView (or UIView subclass)" in title

**Comment by alldritt** [comment]
Yes, it should.  For some reason I cannot find a way to change the repository's description.

**Comment by yoitsro** [comment]
I vote that it's kept. Who doesn't love a sunclass?! ☀️

**Comment by alldritt** [comment]
👍
